# Generated by Django 6.0.5 on 2026-05-24 22:49

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Human-readable name for this parking lot, e.g. 'Main Lot' or 'North Garage'.", max_length=200)),
            ],
            options={
                'verbose_name': 'parking lot',
                'verbose_name_plural': 'parking lots',
            },
        ),
        migrations.CreateModel(
            name='LicensePlate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_text', models.CharField(help_text='License plate text, normalized: whitespace stripped, uppercase only.', max_length=20)),
                ('is_primary', models.BooleanField(default=False, help_text="Whether this is the user's primary plate (shown by default in the UI).")),
                ('label', models.CharField(blank=True, default='', help_text="Optional label to identify this vehicle, e.g. 'Daily Driver' or 'Work Truck'.", max_length=100)),
                ('user', models.ForeignKey(help_text='The user account that owns this license plate.', on_delete=django.db.models.deletion.CASCADE, related_name='plates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'license plate',
                'verbose_name_plural': 'license plates',
                'unique_together': {('user', 'plate_text')},
            },
        ),
        migrations.CreateModel(
            name='LotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Rate per billing unit (in dollars). Always stored as Decimal, never float.', max_digits=8)),
                ('billing_unit', models.CharField(choices=[('hour', 'Per Hour'), ('minute', 'Per Minute')], default='hour', help_text='Whether to charge per full hour or per full minute.', max_length=10)),
                ('grace_period_minutes', models.IntegerField(default=15, help_text='Sessions shorter than this many minutes are free (charged $0.00).')),
                ('daily_cap_enabled', models.BooleanField(default=False, help_text='If True, charge per session is capped at daily_cap_amount.')),
                ('daily_cap_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum charge per session. Only enforced when daily_cap_enabled=True.', max_digits=8, null=True)),
                ('image_retention_days', models.IntegerField(blank=True, help_text='Delete uploaded images older than this many days. Null means keep forever.', null=True)),
                ('confidence_threshold', models.FloatField(default=0.6, help_text='CV pipeline confidence threshold (0.0–1.0). Detections below this score are flagged as low-confidence and queued for review.')),
                ('lot', models.OneToOneField(help_text='The parking lot these settings apply to.', on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='parking.parkinglot')),
            ],
            options={
                'verbose_name': 'lot settings',
                'verbose_name_plural': 'lot settings',
            },
        ),
        migrations.CreateModel(
            name='ParkingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_text', models.CharField(help_text='Normalized license plate for this session (whitespace stripped, uppercase).', max_length=20)),
                ('entry_time', models.DateTimeField(help_text='UTC timestamp when the car entered the lot.')),
                ('exit_time', models.DateTimeField(blank=True, help_text='UTC timestamp when the car exited. Null if the session is still active.', null=True)),
                ('duration_seconds', models.IntegerField(default=0, help_text='Total session duration in seconds. Calculated and stored at exit.')),
                ('charge_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Final charge for this session in dollars. Always use Decimal, never float.', max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('void', 'Void')], db_index=True, default='active', help_text='Current lifecycle state of the session.', max_length=20)),
                ('has_duplicate_warning', models.BooleanField(default=False, help_text='True if this session was opened while the plate already had an active session. Indicates the previous session was auto-voided.')),
                ('was_orphaned', models.BooleanField(default=False, help_text='True if this session was voided because the same plate entered the lot again before this session was closed.')),
                ('license_plate', models.ForeignKey(blank=True, help_text='Registered plate record linked to this session. Null for guest plates.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='parking.licenseplate')),
                ('lot', models.ForeignKey(help_text='The parking lot where this session occurred.', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='parking.parkinglot')),
                ('user', models.ForeignKey(blank=True, help_text='User who owns the plate. Null for guest plates.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'parking session',
                'verbose_name_plural': 'parking sessions',
            },
        ),
        migrations.CreateModel(
            name='PlateDetectionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Uploaded plate image. Stored in MEDIA_ROOT/plates/.', upload_to='plates/')),
                ('raw_plate_text', models.CharField(help_text='Plate text as read by the CV pipeline before normalization.', max_length=20)),
                ('confidence_score', models.FloatField(help_text='CV recognizer confidence score, 0.0–1.0.')),
                ('event_type', models.CharField(choices=[('entry', 'Entry'), ('exit', 'Exit')], help_text='Whether this is an entry or exit detection event.', max_length=10)),
                ('is_low_confidence', models.BooleanField(default=False, help_text="True if confidence_score was below the lot's confidence_threshold.")),
                ('manually_corrected', models.BooleanField(default=False, help_text='True if an operator has manually verified and corrected this detection.')),
                ('corrected_plate', models.CharField(blank=True, help_text='Operator-corrected plate text. Set only when manually_corrected=True.', max_length=20, null=True)),
                ('bounding_box', models.JSONField(default=list, help_text='Plate bounding box [x, y, w, h] in normalized 0–1 coordinates.')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='UTC timestamp when this detection event was created.')),
                ('session', models.ForeignKey(blank=True, help_text='The parking session this detection is linked to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detection_events', to='parking.parkingsession')),
            ],
            options={
                'verbose_name': 'plate detection event',
                'verbose_name_plural': 'plate detection events',
            },
        ),
        migrations.AddIndex(
            model_name='parkingsession',
            index=models.Index(fields=['plate_text', 'status'], name='session_plate_status_idx'),
        ),
        migrations.AddIndex(
            model_name='parkingsession',
            index=models.Index(fields=['lot', 'status'], name='session_lot_status_idx'),
        ),
        migrations.AddIndex(
            model_name='platedetectionevent',
            index=models.Index(fields=['timestamp'], name='detection_event_timestamp_idx'),
        ),
    ]
