# Generated by Django 5.1.15 on 2026-06-09 22:51

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_lotsettings_validators'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='licenseplate',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='name',
            field=models.CharField(help_text="Human-readable name for this parking lot, e.g. 'Main Lot' or 'North Garage'.", max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='parkingsession',
            name='charge_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Final charge for this session in dollars. Always use Decimal, never float.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='parkingsession',
            name='lot',
            field=models.ForeignKey(help_text='The parking lot where this session occurred.', on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='parking.parkinglot'),
        ),
        migrations.AlterField(
            model_name='parkingsession',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('void', 'Void')], default='active', help_text='Current lifecycle state of the session.', max_length=20),
        ),
        migrations.AlterField(
            model_name='platedetectionevent',
            name='confidence_score',
            field=models.FloatField(help_text='CV recognizer confidence score, 0.0–1.0.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddIndex(
            model_name='parkingsession',
            index=models.Index(condition=models.Q(('status', 'active')), fields=['plate_text'], name='session_active_plate_idx'),
        ),
        migrations.AddIndex(
            model_name='parkingsession',
            index=models.Index(condition=models.Q(('status', 'active')), fields=['lot'], name='session_active_lot_idx'),
        ),
        migrations.AddIndex(
            model_name='platedetectionevent',
            index=models.Index(condition=models.Q(('is_low_confidence', True), ('manually_corrected', False)), fields=['is_low_confidence'], name='detection_unreviewed_idx'),
        ),
        migrations.AddConstraint(
            model_name='licenseplate',
            constraint=models.UniqueConstraint(fields=('user', 'plate_text'), name='licenseplate_user_plate_unique'),
        ),
        migrations.AddConstraint(
            model_name='parkingsession',
            constraint=models.CheckConstraint(condition=models.Q(('charge_amount__gte', Decimal('0.00'))), name='session_charge_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='parkingsession',
            constraint=models.CheckConstraint(condition=models.Q(('exit_time__isnull', True), ('exit_time__gt', models.F('entry_time')), _connector='OR'), name='session_exit_after_entry'),
        ),
        migrations.AddConstraint(
            model_name='parkingsession',
            constraint=models.CheckConstraint(condition=models.Q(('duration_seconds__gte', 0)), name='session_duration_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='parkingsession',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'void'), _negated=True), ('charge_amount', Decimal('0.00')), _connector='OR'), name='session_void_no_charge'),
        ),
        migrations.AddConstraint(
            model_name='platedetectionevent',
            constraint=models.CheckConstraint(condition=models.Q(('confidence_score__gte', 0.0), ('confidence_score__lte', 1.0)), name='event_confidence_score_range'),
        ),
    ]
