# Generated by Codex on 2026-06-16

import django.db.models.deletion
from django.db import migrations, models


def backfill_event_lots(apps, schema_editor):
    """
    Copy lot context from linked sessions onto historical detection events.

    WHY: pre-existing entry/exit events already know their lot through the
    session relation. Unmatched legacy events remain null because there is no
    reliable lot source to infer from.
    """
    PlateDetectionEvent = apps.get_model("parking", "PlateDetectionEvent")
    for event in (
        PlateDetectionEvent.objects.filter(lot__isnull=True, session__isnull=False)
        .select_related("session")
        .iterator()
    ):
        event.lot_id = event.session.lot_id
        event.save(update_fields=["lot"])


class Migration(migrations.Migration):

    dependencies = [
        ("parking", "0003_alter_licenseplate_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="platedetectionevent",
            name="lot",
            field=models.ForeignKey(
                blank=True,
                help_text="Parking lot where this detection occurred.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="detection_events",
                to="parking.parkinglot",
            ),
        ),
        migrations.RunPython(backfill_event_lots, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name="platedetectionevent",
            index=models.Index(
                fields=["lot", "event_type"],
                name="detection_lot_event_idx",
            ),
        ),
    ]
