# Generated by Django 5.1.15 on 2026-06-17 03:19

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0004_platedetectionevent_lot_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotsettings',
            name='grace_period_minutes',
            field=models.IntegerField(default=15, help_text='Sessions shorter than this many minutes are free (charged $0.00). Capped at 1440 (24h) so a stray value cannot make all parking free.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1440)]),
        ),
        migrations.AddConstraint(
            model_name='lotsettings',
            constraint=models.CheckConstraint(condition=models.Q(('billing_unit__in', ['hour', 'minute'])), name='lotsettings_billing_unit_valid'),
        ),
        migrations.AddConstraint(
            model_name='lotsettings',
            constraint=models.CheckConstraint(condition=models.Q(('grace_period_minutes__gte', 0), ('grace_period_minutes__lte', 1440)), name='lotsettings_grace_period_range'),
        ),
        migrations.AddConstraint(
            model_name='parkingsession',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('lot', 'plate_text'), name='session_one_active_per_lot_plate'),
        ),
    ]
